In [1]:
import webdataset as wds
import torch
import io
import numpy as np
import time
import os

In [2]:
bucket = "taturabe-dataset"
prefix = "dataset/webdataset"

In [3]:
url = f"s3://{bucket}/{prefix}/shard/" + "npy_webdataset-{0000..0009}.tar"
url = f"pipe:aws s3 cp {url} - || true"
print(url)

pipe:aws s3 cp s3://taturabe-dataset/dataset/webdataset/shard/npy_webdataset-{0000..0009}.tar - || true


In [4]:
dataset = wds.WebDataset(url, shardshuffle=False, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy").batched(5)
loader = wds.WebLoader(dataset, num_workers=0, batch_size=None)

for inp, out in loader:
    print(out)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14])
tensor([15, 16, 17, 18, 19])
tensor([20, 21, 22, 23, 24])
tensor([25, 26, 27, 28, 29])
tensor([30, 31, 32, 33, 34])
tensor([35, 36, 37, 38, 39])
tensor([40, 41, 42, 43, 44])
tensor([45, 46, 47, 48, 49])
tensor([50, 51, 52, 53, 54])
tensor([55, 56, 57, 58, 59])
tensor([60, 61, 62, 63, 64])
tensor([65, 66, 67, 68, 69])
tensor([70, 71, 72, 73, 74])
tensor([75, 76, 77, 78, 79])
tensor([80, 81, 82, 83, 84])
tensor([85, 86, 87, 88, 89])
tensor([90, 91, 92, 93, 94])
tensor([95, 96, 97, 98, 99])


In [5]:
dataset = wds.WebDataset(url, shardshuffle=False, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy")
loader = wds.WebLoader(dataset, num_workers=0, batch_size=5)

for inp, out in loader:
    print(out)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14])
tensor([15, 16, 17, 18, 19])
tensor([20, 21, 22, 23, 24])
tensor([25, 26, 27, 28, 29])
tensor([30, 31, 32, 33, 34])
tensor([35, 36, 37, 38, 39])
tensor([40, 41, 42, 43, 44])
tensor([45, 46, 47, 48, 49])
tensor([50, 51, 52, 53, 54])
tensor([55, 56, 57, 58, 59])
tensor([60, 61, 62, 63, 64])
tensor([65, 66, 67, 68, 69])
tensor([70, 71, 72, 73, 74])
tensor([75, 76, 77, 78, 79])
tensor([80, 81, 82, 83, 84])
tensor([85, 86, 87, 88, 89])
tensor([90, 91, 92, 93, 94])
tensor([95, 96, 97, 98, 99])


In [ ]:
dataset = wds.WebDataset(url, shardshuffle=False, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy")
loader = wds.WebLoader(dataset, num_workers=2, batch_size=5)

for inp, out in loader:
    print(out)

In [ ]:
dataset = wds.WebDataset(url, shardshuffle=True, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy")
loader = wds.WebLoader(dataset, num_workers=2, batch_size=5)

for inp, out in loader:
    print(out)

In [ ]:
dataset = wds.WebDataset(url, shardshuffle=True, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy")
loader = wds.WebLoader(dataset, num_workers=2, batch_size=5,shuffle=True)

for inp, out in loader:
    print(out)

In [ ]:
dataset = wds.WebDataset(url, shardshuffle=True, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy")
loader = wds.WebLoader(dataset, num_workers=2, batch_size=5).shuffle(100)

for inp, out in loader:
    print(out)

In [ ]:
dataset = wds.WebDataset(url, shardshuffle=False, cache_dir=None).decode()
dataset = dataset.to_tuple("input.npy", "output.npy").shuffle(2).batched(3)
loader = wds.WebLoader(dataset, num_workers=3)

for inp, out in loader:
    print(out)